### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### teszt
get {{host}}/api/

### login
# @name login
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123"
}

###
@token = {{login.response.body.user.token}}

### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}


### get products
GET  {{host}}/api/products

### post products
POST  {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "Bogyós",
    "name": "Málna2",
    "description": "Kézzel termelt egészség",
    "picture": "https:\/\/hur.webmania.cc\/img\/malna.jpg",
    "price": 8000,
    "stock": 500
}


### patch products
PATCH  {{host}}/api/products/20
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "Bogyósok",
    "price": 4000
}

### delete product by id
DELETE  {{host}}/api/products/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
