### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### teszt
get {{host}}/api/


### get all 
GET  {{host}}/api/instruments

### get 
GET  {{host}}/api/instruments/1

### post 
POST  {{host}}/api/instruments
Accept: application/json
Content-Type: application/json


{
    "id": 10000,
    "name": "sárga furulya",
    "description": "hangszer",
    "price": 8000,
    "stock": 500
}


### patch products
PATCH  {{host}}/api/instruments/20
Accept: application/json
Content-Type: application/json


{
    "id": 20,
    "price": 4000
}

### delete product by id
DELETE  {{host}}/api/instruments
Accept: application/json
Content-Type: application/json

